version: "3.8"
services:
  bot:
    restart: unless-stopped
    image: telegrampay
    build:
      context: .
    env_file: stack.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: unless-stopped
    env_file: stack.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_user -d your_db"]
      interval: 5s
      timeout: 5s
      retries: 10


networks: {}
volumes:
  postgres_data:
